# Generated by Django 6.0.7 on 2026-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('SUPPLIER', 'Supplier'), ('DELIVERY_RIDER', 'Delivery Rider'), ('DELIVERY', 'Legacy Delivery Rider')], default='CUSTOMER', max_length=20),
        ),
    ]
