# Generated by Django 6.0.7 on 2026-09-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('SUPPLIER', 'Supplier'), ('DELIVERY_RIDER', 'Delivery Rider')], default='CUSTOMER', max_length=20),
        ),
    ]
