# Generated by Django 6.0.7 on 2026-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Information', 'Information')], default='Information', max_length=30),
        ),
    ]
