# Generated by Django 6.0.7 on 2026-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Low Stock Alert', 'Low Stock Alert'), ('Product Approved', 'Product Approved'), ('Product Rejected', 'Product Rejected'), ('Admin Message', 'Admin Message'), ('Payment Update', 'Payment Update'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Refund Requested', 'Refund Requested'), ('Refund Approved', 'Refund Approved'), ('Refund Rejected', 'Refund Rejected'), ('Refund Completed', 'Refund Completed'), ('Information', 'Information')], default='Information', max_length=30),
        ),
    ]
