# Generated by Django 6.0.7 on 2026-08-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_charge_order_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('SSLCommerz', 'SSLCommerz'), ('Stripe', 'Stripe')], default='Cash on Delivery', max_length=30),
        ),
    ]
