# Generated by Django 6.0.7 on 2026-09-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('FULL', 'Full Refund'), ('PARTIAL', 'Partial Refund')], default='FULL', max_length=10),
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='orders.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='orders.refund')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refund', 'order_item'), name='unique_refund_order_item')],
            },
        ),
    ]
