# Generated by Django 6.0.7 on 2026-09-09 05:05

import django.core.validators
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_refund_refund_type_refunditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models.refund_photo_upload_path, validators=[orders.models.validate_refund_photo_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_photos', to='orders.refund')),
            ],
        ),
    ]
