# Generated by Django 6.0.7 on 2026-09-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_refundphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
