# Generated by Django 6.0.7 on 2026-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_created_by_order_offline_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
