# Generated by Django 5.2.15 on 2026-09-20 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_orderitem_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_refund_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='pickup_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='rider_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Return Pending', 'Return Pending'), ('Rider Assigned', 'Rider Assigned'), ('Rider Accepted', 'Rider Accepted'), ('Picked Up', 'Picked Up'), ('Rejected', 'Rejected'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Pickup Expired', 'Pickup Expired')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='refundstatushistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Return Pending', 'Return Pending'), ('Rider Assigned', 'Rider Assigned'), ('Rider Accepted', 'Rider Accepted'), ('Picked Up', 'Picked Up'), ('Rejected', 'Rejected'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Pickup Expired', 'Pickup Expired')], max_length=20),
        ),
    ]
