# Generated by Django 5.2.15 on 2026-09-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryotp'),
        ('orders', '0024_refund_assigned_at_refund_assigned_rider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryotp',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_otp', to='orders.refund'),
        ),
        migrations.AlterField(
            model_name='deliveryotp',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='delivery.delivery'),
        ),
    ]
