# Generated by Django 6.0.7 on 2026-08-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_delivery_charge_order_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('gateway', models.CharField(default='SSLCommerz', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=120)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=120)),
                ('validation_id', models.CharField(blank=True, max_length=120)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('card_brand', models.CharField(blank=True, max_length=100)),
                ('card_issuer', models.CharField(blank=True, max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
