# Generated by Django 6.0.7 on 2026-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_options_supplier_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
