# Generated by Django 6.0.7 on 2026-09-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_replenishmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('replenishment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='suppliers.replenishmentrequest')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('replenishment_request', 'new_status'), name='unique_replenishment_status_event')],
            },
        ),
    ]
